# Generated by Django 5.2.16 on 2026-07-28 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advertising", "0004_campaign_target_acos"),
        ("reports", "0001_initial"),
        ("stores", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyRuleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("HIGH_ACOS", "High ACOS"),
                            ("HIGH_SPEND_NO_ORDERS", "High spend with no orders"),
                            (
                                "HIGH_CLICKS_LOW_CONVERSION",
                                "High clicks with low conversion",
                            ),
                            ("LOW_IMPRESSIONS", "Low impressions"),
                        ],
                        max_length=64,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("scope_key", models.CharField(default="SYSTEM", max_length=160)),
                ("configuration", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anomaly_rule_versions",
                        to="advertising.campaign",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anomaly_rule_versions",
                        to="stores.advertisingprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anomaly_rule_versions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_anomaly_rule_version",
            },
        ),
        migrations.CreateModel(
            name="CampaignDailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                ("currency_code", models.CharField(max_length=3)),
                ("impressions", models.PositiveBigIntegerField()),
                ("clicks", models.PositiveBigIntegerField()),
                ("spend", models.DecimalField(decimal_places=4, max_digits=20)),
                ("orders", models.PositiveBigIntegerField()),
                ("sales", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "daily_budget_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "state_snapshot",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_metrics",
                        to="advertising.campaign",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_daily_metrics",
                        to="stores.advertisingprofile",
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_daily_metrics",
                        to="reports.importbatch",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_campaign_daily_metric",
            },
        ),
        migrations.CreateModel(
            name="AnomalyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("ANOMALY", "Anomaly"),
                            ("INSUFFICIENT_DATA", "Insufficient data"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "observed_value",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=96)),
                ("explanation", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anomaly_records",
                        to="reports.importbatch",
                    ),
                ),
                (
                    "rule_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="analytics.anomalyruleversion",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anomaly_records",
                        to="analytics.campaigndailymetric",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_anomaly_record",
            },
        ),
        migrations.CreateModel(
            name="CampaignMetricRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_values", models.JSONField(default=dict)),
                ("current_values", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="analytics.campaigndailymetric",
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_metric_revisions",
                        to="reports.importbatch",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_campaign_metric_revision",
            },
        ),
        migrations.AddIndex(
            model_name="anomalyruleversion",
            index=models.Index(
                fields=["code", "is_active"], name="analytics_rule_code_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="anomalyruleversion",
            constraint=models.UniqueConstraint(
                fields=("code", "version", "scope_key"),
                name="analytics_rule_scope_version_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="campaigndailymetric",
            index=models.Index(
                fields=["profile", "report_date"], name="anly_camp_profile_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaigndailymetric",
            index=models.Index(
                fields=["campaign", "report_date"], name="anly_camp_entity_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaigndailymetric",
            constraint=models.UniqueConstraint(
                fields=("profile", "campaign", "report_date"),
                name="analytics_campaign_daily_natural_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="anomalyrecord",
            index=models.Index(
                fields=["status", "risk_level", "-created_at"],
                name="anly_anom_status_risk_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="anomalyrecord",
            constraint=models.UniqueConstraint(
                fields=("metric", "rule_version", "source_batch"),
                name="analytics_anomaly_metric_rule_batch_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignmetricrevision",
            constraint=models.UniqueConstraint(
                fields=("metric", "source_batch"),
                name="analytics_metric_revision_batch_uniq",
            ),
        ),
    ]
