# Generated by Django 5.2.16 on 2026-07-28 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertising', '0003_campaign_target_acos'),
        ('reports', '0001_initial'),
        ('stores', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyRuleVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('SYSTEM', 'System'), ('TENANT', 'Tenant'), ('PROFILE', 'Profile'), ('CAMPAIGN', 'Campaign')], max_length=16)),
                ('version', models.PositiveIntegerField()),
                ('thresholds', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advertising.campaign')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.advertisingprofile')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'analytics_anomaly_rule_version',
            },
        ),
        migrations.CreateModel(
            name='CampaignDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('ctr', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('cpc', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('cvr', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('acos', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('roas', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('invalid_reasons', models.JSONField(default=dict)),
                ('currency', models.CharField(max_length=3)),
                ('budget_snapshot', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('state_snapshot', models.CharField(max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='advertising.campaign')),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.importbatch')),
            ],
            options={
                'db_table': 'analytics_campaign_daily_metric',
            },
        ),
        migrations.CreateModel(
            name='AnomalyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical (reserved)')], max_length=16)),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.anomalyruleversion')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='analytics.campaigndailymetric')),
            ],
            options={
                'db_table': 'analytics_anomaly_record',
            },
        ),
        migrations.CreateModel(
            name='SearchTermDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('ctr', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('cpc', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('cvr', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('acos', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('roas', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('invalid_reasons', models.JSONField(default=dict)),
                ('currency', models.CharField(max_length=3)),
                ('search_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='advertising.searchterm')),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.importbatch')),
            ],
            options={
                'db_table': 'analytics_search_term_daily_metric',
            },
        ),
        migrations.CreateModel(
            name='TargetingDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('ctr', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('cpc', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('cvr', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('acos', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('roas', models.DecimalField(decimal_places=8, max_digits=16, null=True)),
                ('invalid_reasons', models.JSONField(default=dict)),
                ('currency', models.CharField(max_length=3)),
                ('targeting_type', models.CharField(max_length=16)),
                ('bid_snapshot', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('state_snapshot', models.CharField(max_length=16)),
                ('keyword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advertising.keyword')),
                ('product_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advertising.producttarget')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.advertisingprofile')),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.importbatch')),
            ],
            options={
                'db_table': 'analytics_targeting_daily_metric',
            },
        ),
        migrations.AddConstraint(
            model_name='anomalyruleversion',
            constraint=models.UniqueConstraint(fields=('code', 'scope', 'tenant', 'profile', 'campaign', 'version'), name='analytics_rule_scope_version_uniq'),
        ),
        migrations.AddIndex(
            model_name='campaigndailymetric',
            index=models.Index(fields=['campaign', 'business_date'], name='analytics_campaign_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaigndailymetric',
            constraint=models.UniqueConstraint(fields=('campaign', 'business_date'), name='analytics_campaign_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='anomalyrecord',
            constraint=models.UniqueConstraint(fields=('metric', 'rule_version'), name='analytics_anomaly_metric_rule_uniq'),
        ),
        migrations.AddIndex(
            model_name='searchtermdailymetric',
            index=models.Index(fields=['business_date'], name='analytics_searchterm_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchtermdailymetric',
            constraint=models.UniqueConstraint(fields=('search_term', 'business_date'), name='analytics_searchterm_date_uniq'),
        ),
        migrations.AddIndex(
            model_name='targetingdailymetric',
            index=models.Index(fields=['profile', 'business_date'], name='analytics_tgt_prof_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='targetingdailymetric',
            constraint=models.UniqueConstraint(fields=('keyword', 'business_date'), name='analytics_keyword_date_uniq'),
        ),
        migrations.AddConstraint(
            model_name='targetingdailymetric',
            constraint=models.UniqueConstraint(fields=('product_target', 'business_date'), name='analytics_target_date_uniq'),
        ),
    ]
