# Generated by Django 5.2.16 on 2026-07-28 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising", "0004_campaign_target_acos"),
        ("analytics", "0001_initial"),
        ("reports", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchTermDailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField()),
                ("targeting_expression_hash", models.CharField(max_length=64)),
                ("targeting_expression_snapshot", models.CharField(max_length=1000)),
                ("currency_code", models.CharField(max_length=3)),
                ("impressions", models.PositiveBigIntegerField()),
                ("clicks", models.PositiveBigIntegerField()),
                ("spend", models.DecimalField(decimal_places=4, max_digits=20)),
                ("orders", models.PositiveBigIntegerField()),
                ("sales", models.DecimalField(decimal_places=4, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="search_term_daily_metrics",
                        to="advertising.adgroup",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="search_term_daily_metrics",
                        to="advertising.campaign",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="search_term_daily_metrics",
                        to="stores.advertisingprofile",
                    ),
                ),
                (
                    "search_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_metrics",
                        to="advertising.searchterm",
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="search_term_daily_metrics",
                        to="reports.importbatch",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_search_term_daily_metric",
            },
        ),
        migrations.CreateModel(
            name="SearchTermMetricRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_values", models.JSONField(default=dict)),
                ("current_values", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="analytics.searchtermdailymetric",
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="search_term_metric_revisions",
                        to="reports.importbatch",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_search_term_metric_revision",
            },
        ),
        migrations.CreateModel(
            name="TargetingDailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("KEYWORD", "Keyword"),
                            ("PRODUCT_TARGET", "Product Target"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_key", models.CharField(max_length=160)),
                ("report_date", models.DateField()),
                ("currency_code", models.CharField(max_length=3)),
                ("impressions", models.PositiveBigIntegerField()),
                ("clicks", models.PositiveBigIntegerField()),
                ("spend", models.DecimalField(decimal_places=4, max_digits=20)),
                ("orders", models.PositiveBigIntegerField()),
                ("sales", models.DecimalField(decimal_places=4, max_digits=20)),
                (
                    "bid_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "state_snapshot",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="targeting_daily_metrics",
                        to="advertising.adgroup",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="targeting_daily_metrics",
                        to="advertising.campaign",
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_metrics",
                        to="advertising.keyword",
                    ),
                ),
                (
                    "product_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_metrics",
                        to="advertising.producttarget",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="targeting_daily_metrics",
                        to="stores.advertisingprofile",
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="targeting_daily_metrics",
                        to="reports.importbatch",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_targeting_daily_metric",
            },
        ),
        migrations.CreateModel(
            name="TargetingMetricRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_values", models.JSONField(default=dict)),
                ("current_values", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="analytics.targetingdailymetric",
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="targeting_metric_revisions",
                        to="reports.importbatch",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_targeting_metric_revision",
            },
        ),
        migrations.AddIndex(
            model_name="searchtermdailymetric",
            index=models.Index(
                fields=["profile", "report_date"], name="anly_search_profile_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchtermdailymetric",
            index=models.Index(
                fields=["search_term", "report_date"],
                name="anly_search_entity_date_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchtermdailymetric",
            constraint=models.UniqueConstraint(
                fields=(
                    "profile",
                    "campaign",
                    "ad_group",
                    "search_term",
                    "report_date",
                    "targeting_expression_hash",
                ),
                name="anly_search_term_daily_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchtermmetricrevision",
            constraint=models.UniqueConstraint(
                fields=("metric", "source_batch"),
                name="anly_search_revision_batch_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="targetingdailymetric",
            index=models.Index(
                fields=["profile", "report_date", "target_type"],
                name="anly_target_profile_date_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="targetingdailymetric",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("keyword__isnull", False),
                        ("product_target__isnull", True),
                        ("target_type", "KEYWORD"),
                    ),
                    models.Q(
                        ("keyword__isnull", True),
                        ("product_target__isnull", False),
                        ("target_type", "PRODUCT_TARGET"),
                    ),
                    _connector="OR",
                ),
                name="anly_target_metric_entity_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="targetingdailymetric",
            constraint=models.UniqueConstraint(
                fields=("profile", "target_key", "report_date"),
                name="anly_target_entity_daily_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="targetingmetricrevision",
            constraint=models.UniqueConstraint(
                fields=("metric", "source_batch"),
                name="anly_target_revision_batch_uniq",
            ),
        ),
    ]
