# Generated by Django 5.2.16 on 2026-07-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_searchtermdailymetric_searchtermmetricrevision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigndailymetric",
            name="snapshot_hour_local",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anomalyruleversion",
            name="code",
            field=models.CharField(
                choices=[
                    ("HIGH_ACOS", "High ACOS"),
                    ("HIGH_SPEND_NO_ORDERS", "High spend with no orders"),
                    ("HIGH_CLICKS_LOW_CONVERSION", "High clicks with low conversion"),
                    ("BUDGET_EARLY_EXHAUSTION", "Budget exhausted early"),
                    ("LOW_IMPRESSIONS", "Low impressions"),
                    ("LOW_CLICKS", "Low clicks"),
                ],
                max_length=64,
            ),
        ),
    ]
