# Generated by Django 5.2.16 on 2026-07-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_campaigndailymetric_snapshot_hour_local_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigndailymetric",
            name="calculation_reasons",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="searchtermdailymetric",
            name="calculation_reasons",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="targetingdailymetric",
            name="calculation_reasons",
            field=models.JSONField(default=dict),
        ),
    ]
