# Generated by Django 5.2.16 on 2026-07-28 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_code",
                    models.CharField(
                        choices=[
                            ("DATA_ANALYSIS", "Data analysis"),
                            ("ANOMALY_DIAGNOSIS", "Anomaly diagnosis"),
                            ("BUDGET_ANALYSIS", "Budget analysis"),
                            ("COMPOSITE_STRATEGY", "Composite strategy"),
                        ],
                        default="COMPOSITE_STRATEGY",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(default="agent-result-v1", max_length=32),
                ),
                ("celery_task_id", models.CharField(max_length=128)),
                ("input_snapshot", models.JSONField(default=dict)),
                ("output_result", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, max_length=96)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_runs",
                        to="stores.advertisingprofile",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_runs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "agent_run",
                "indexes": [
                    models.Index(
                        fields=["tenant", "profile", "-created_at"],
                        name="agent_run_scope_created_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="agent_run_status_created_idx",
                    ),
                ],
            },
        ),
    ]
