# Generated by Django 5.2.16 on 2026-07-28 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("stores", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="analysistask",
            index=models.Index(
                fields=["tenant", "profile", "created_at"],
                name="agent_task_scope_created_idx",
            ),
        ),
    ]
