# Generated by Django 5.2.16 on 2026-07-28 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advertising", "0004_campaign_target_acos"),
        ("agents", "0001_initial"),
        ("stores", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMInvocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_code", models.CharField(max_length=64)),
                ("agent_code", models.CharField(max_length=32)),
                ("request_payload", models.JSONField(default=dict)),
                ("response_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="llm_invocations",
                        to="agents.agentrun",
                    ),
                ),
            ],
            options={
                "db_table": "ai_llm_invocation",
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("UPDATE_CAMPAIGN_BUDGET", "Update Campaign budget"),
                            ("SET_CAMPAIGN_STATE", "Pause or enable Campaign"),
                            ("UPDATE_KEYWORD_BID", "Update Keyword bid"),
                            ("SET_KEYWORD_STATE", "Pause or enable Keyword"),
                            ("UPDATE_PRODUCT_TARGET_BID", "Update Product Target bid"),
                            (
                                "SET_PRODUCT_TARGET_STATE",
                                "Pause or enable Product Target",
                            ),
                            ("CREATE_KEYWORD", "Create Keyword"),
                            ("CREATE_NEGATIVE_KEYWORD", "Create Negative Keyword"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUPERSEDED", "Superseded"),
                            ("ACCEPTED", "Accepted"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("current_revision_number", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="agents.agentrun",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="advertising.campaign",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="stores.advertisingprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ai_recommendation",
            },
        ),
        migrations.CreateModel(
            name="RecommendationRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("schema_version", models.CharField(max_length=32)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("UPDATE_CAMPAIGN_BUDGET", "Update Campaign budget"),
                            ("SET_CAMPAIGN_STATE", "Pause or enable Campaign"),
                            ("UPDATE_KEYWORD_BID", "Update Keyword bid"),
                            ("SET_KEYWORD_STATE", "Pause or enable Keyword"),
                            ("UPDATE_PRODUCT_TARGET_BID", "Update Product Target bid"),
                            (
                                "SET_PRODUCT_TARGET_STATE",
                                "Pause or enable Product Target",
                            ),
                            ("CREATE_KEYWORD", "Create Keyword"),
                            ("CREATE_NEGATIVE_KEYWORD", "Create Negative Keyword"),
                        ],
                        max_length=64,
                    ),
                ),
                ("object_type", models.CharField(max_length=64)),
                ("object_id", models.CharField(max_length=128)),
                ("before_value", models.JSONField(default=dict)),
                ("after_value", models.JSONField(default=dict)),
                ("reason", models.CharField(max_length=1000)),
                ("evidence", models.JSONField(default=list)),
                ("risk_level", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="recommendations.recommendation",
                    ),
                ),
            ],
            options={
                "db_table": "ai_recommendation_revision",
            },
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["tenant", "profile", "status", "-created_at"],
                name="ai_recommend_scope_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.UniqueConstraint(
                fields=("agent_run", "campaign", "action_type"),
                name="ai_recommendation_run_object_action_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationrevision",
            constraint=models.UniqueConstraint(
                fields=("recommendation", "revision_number"),
                name="ai_recommendation_revision_uniq",
            ),
        ),
    ]
