# Generated by Django 5.2.16 on 2026-07-28 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("stores", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="OPEN", max_length=16)),
                ("action_type", models.CharField(max_length=64)),
                ("object_type", models.CharField(max_length=64)),
                ("object_id", models.CharField(max_length=128)),
                ("before_value", models.JSONField(default=dict)),
                ("after_value", models.JSONField(default=dict)),
                ("reason", models.TextField()),
                ("evidence", models.JSONField(default=list)),
                ("risk_level", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="agents.analysistask",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stores.advertisingprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "ai_recommendation",
            },
        ),
        migrations.CreateModel(
            name="RecommendationRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("content", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="recommendations.recommendation",
                    ),
                ),
            ],
            options={
                "db_table": "ai_recommendation_revision",
            },
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.UniqueConstraint(
                fields=("analysis_task", "action_type", "object_id"),
                name="ai_recommendation_task_action_obj_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="recommendationrevision",
            constraint=models.UniqueConstraint(
                fields=("recommendation", "version"),
                name="ai_recommendation_revision_uniq",
            ),
        ),
    ]
