# Generated by Django 5.2.16 on 2026-07-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_analysistask_agent_task_scope_created_idx"),
        ("recommendations", "0001_initial"),
        ("stores", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["tenant", "profile", "status", "created_at"],
                name="ai_rec_scope_status_idx",
            ),
        ),
    ]
