# Generated by Django 5.2.16 on 2026-07-28 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=96)),
                ("object_type", models.CharField(blank=True, max_length=96)),
                ("object_id", models.CharField(blank=True, max_length=128)),
                ("request_id", models.CharField(max_length=128)),
                ("task_id", models.CharField(blank=True, max_length=128)),
                ("before_data", models.JSONField(default=dict)),
                ("after_data", models.JSONField(default=dict)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "audit_log",
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="audit_tenant_created_idx",
                    ),
                    models.Index(
                        fields=["event", "-created_at"], name="audit_event_created_idx"
                    ),
                ],
            },
        ),
    ]
