# Generated by Django 5.2.16 on 2026-07-31 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_authentication"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("SCM_MERCHANT_ADMIN", "SCM Merchant Admin")],
                        max_length=32,
                    ),
                ),
                ("external_user_id", models.CharField(max_length=128)),
                ("external_merchant_id", models.CharField(max_length=128)),
                ("identifier", models.CharField(max_length=254)),
                ("last_authenticated_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sys_external_identity",
                "indexes": [
                    models.Index(
                        fields=["user", "source"], name="sys_external_user_source_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_user_id"),
                        name="sys_external_identity_user_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("source", "identifier"),
                        name="sys_external_identity_name_uniq",
                    ),
                ],
            },
        ),
    ]
