"""Declarative rule definitions for the 44 audit checks."""

from __future__ import annotations

from .models import AuditRule

DEFAULT_SECURITY_RULES: tuple[AuditRule, ...] = (
    AuditRule(
        rule_id="SEC-SENSITIVE-001",
        category="security",
        severity="critical",
        description="No hardcoded AWS keys (AKIA prefix), Bearer tokens, or private key markers in source files",
        check_function="check_hardcoded_secrets",
    ),
    AuditRule(
        rule_id="SEC-SENSITIVE-002",
        category="security",
        severity="high",
        description=".gitignore excludes .env and .env.* while preserving .env.example",
        check_function="check_gitignore_env_exclusion",
    ),
    AuditRule(
        rule_id="SEC-SENSITIVE-003",
        category="security",
        severity="high",
        description="LLMReasonerConfig.api_key marked repr=False; safe_description() does not return actual key values",
        check_function="check_api_key_repr_false",
    ),
    AuditRule(
        rule_id="SEC-SENSITIVE-004",
        category="security",
        severity="high",
        description="AuditCollector FORBIDDEN_METADATA_KEYS covers access_token, refresh_token, authorization_header, secret, password",
        check_function="check_forbidden_metadata_keys",
    ),
    AuditRule(
        rule_id="SEC-SENSITIVE-005",
        category="security",
        severity="high",
        description="Evaluation reports do not contain API keys, Authorization headers, complete prompts, or raw responses",
        check_function="check_report_no_credentials",
    ),
    AuditRule(
        rule_id="SEC-INJECTION-001",
        category="security",
        severity="critical",
        description="PromptBuilder.build() injects task data via JSON serialization inside <reasoner_input_json> tag, not mixed with system prompt",
        check_function="check_prompt_data_isolation",
    ),
    AuditRule(
        rule_id="SEC-INJECTION-002",
        category="security",
        severity="high",
        description="reasoner-system.md contains Data Trust Boundary declaration stating instructions in data fields have no system authority",
        check_function="check_prompt_trust_boundary",
    ),
    AuditRule(
        rule_id="SEC-INJECTION-003",
        category="security",
        severity="critical",
        description="LLMReasoner._parse() uses json.loads strict parsing; no extraction from Markdown fences; no type coercion",
        check_function="check_strict_json_parsing",
    ),
    AuditRule(
        rule_id="SEC-INJECTION-004",
        category="security",
        severity="high",
        description="load_prompt() uses ALLOWED_PROMPTS whitelist; rejects absolute paths and path traversal",
        check_function="check_prompt_whitelist",
    ),
    AuditRule(
        rule_id="SEC-UNSAFE-001",
        category="security",
        severity="critical",
        description="No eval() or exec() calls in src/; subprocess only for evaluation report git rev-parse",
        check_function="check_no_eval_exec",
    ),
    AuditRule(
        rule_id="SEC-UNSAFE-002",
        category="security",
        severity="high",
        description="No float() calls in src/; business calculations use decimal.Decimal",
        check_function="check_no_float",
    ),
    AuditRule(
        rule_id="SEC-UNSAFE-003",
        category="security",
        severity="high",
        description="_validate_endpoint() requires HTTPS for non-localhost; URL must not contain username/password",
        check_function="check_https_endpoint",
    ),
    AuditRule(
        rule_id="SEC-PROD-001",
        category="security",
        severity="critical",
        description="production_write_called is always False; production writes are unconditionally forbidden",
        check_function="check_production_write_forbidden",
    ),
    AuditRule(
        rule_id="SEC-PROD-002",
        category="security",
        severity="critical",
        description="No *production*adapter*.py file or ProductionAdapter class exists",
        check_function="check_no_production_adapter",
    ),
    AuditRule(
        rule_id="SEC-NETWORK-001",
        category="security",
        severity="high",
        description="CI config sets LLM_PROVIDER=stub and LLM_REAL_CALL_ENABLED=false; default config has reasoner.provider=stub",
        check_function="check_default_offline_mode",
    ),
    AuditRule(
        rule_id="SEC-NETWORK-002",
        category="security",
        severity="high",
        description="load_real_reasoner_config() requires both LLM_REAL_CALL_ENABLED=true and CLI --confirm-real-model double confirmation",
        check_function="check_double_confirmation",
    ),
    AuditRule(
        rule_id="SEC-REDACT-001",
        category="security",
        severity="high",
        description="security.py _SENSITIVE regex covers api_key, bearer, authorization, access_token, refresh_token, secret, password patterns",
        check_function="check_redact_sensitive_patterns",
    ),
    AuditRule(
        rule_id="SEC-REDACT-002",
        category="security",
        severity="medium",
        description="Evaluation report build_real_report() uses safe_base_url_host() to strip credentials from base_url",
        check_function="check_report_url_redaction",
    ),
)

DEFAULT_COMPLIANCE_RULES: tuple[AuditRule, ...] = (
    AuditRule(
        rule_id="COMPLIANCE-CODE-001",
        category="compliance",
        severity="high",
        description="decimal_utils.py parse_decimal() rejects non-string input; decimal_to_string() serializes as string; no float() in business code",
        check_function="check_decimal_enforcement",
    ),
    AuditRule(
        rule_id="COMPLIANCE-CODE-002",
        category="compliance",
        severity="high",
        description="schema_loader.py uses Draft202012Validator; validate_task_input() includes cross-field validation",
        check_function="check_schema_validation",
    ),
    AuditRule(
        rule_id="COMPLIANCE-CODE-003",
        category="compliance",
        severity="high",
        description="ReasonerInput.create() uses freeze() for recursive freezing; MappingProxyType wraps dicts",
        check_function="check_immutable_data",
    ),
    AuditRule(
        rule_id="COMPLIANCE-CODE-004",
        category="compliance",
        severity="high",
        description="ReasonerError contains error_code, safe_message, retryable, provider; __str__ returns safe format",
        check_function="check_structured_errors",
    ),
    AuditRule(
        rule_id="COMPLIANCE-ARCH-001",
        category="compliance",
        severity="high",
        description="Reasoner Protocol defines reason(reasoner_input) -> ReasonerResult; LLMReasoner and ReasonerStub both implement reason()",
        check_function="check_reasoner_contract",
    ),
    AuditRule(
        rule_id="COMPLIANCE-ARCH-002",
        category="compliance",
        severity="medium",
        description="ReasonerInput is immutable; LLMReasoner.reason() returns ReasonerResult without modifying input state",
        check_function="check_reasoner_immutability",
    ),
    AuditRule(
        rule_id="COMPLIANCE-ARCH-003",
        category="compliance",
        severity="medium",
        description="LLMReasoner last_transport_retry_count and call_count are independent; audit events record transport_retry_count and agent_revision_count separately",
        check_function="check_independent_counters",
    ),
    AuditRule(
        rule_id="COMPLIANCE-ARCH-004",
        category="compliance",
        severity="high",
        description="config_loader.py load_config() loads from YAML; validate_config() validates required fields; require_config() has no fallback inference",
        check_function="check_config_loading",
    ),
    AuditRule(
        rule_id="COMPLIANCE-ARCH-005",
        category="compliance",
        severity="high",
        description="AuditCollector record() appends events; validate_audit_event() Schema validates; FORBIDDEN_METADATA_KEYS prohibits credentials",
        check_function="check_audit_append_only",
    ),
    AuditRule(
        rule_id="COMPLIANCE-API-001",
        category="compliance",
        severity="medium",
        description="cli.py accepts only input, --reasoner-mode, --reasoner-provider; errors use INPUT_ERROR/INTERNAL_ERROR prefix",
        check_function="check_cli_interface",
    ),
    AuditRule(
        rule_id="COMPLIANCE-API-002",
        category="compliance",
        severity="high",
        description="output_schema.py validate_reasoner_output() uses independent reasoner-output.schema.json; no lenient parsing",
        check_function="check_output_schema",
    ),
    AuditRule(
        rule_id="COMPLIANCE-ARCH-006",
        category="compliance",
        severity="medium",
        description="preflight.py run_preflight() verifies execution mode, production_write forbidden, and computes digest",
        check_function="check_preflight_contract",
    ),
)

DEFAULT_BOUNDARY_RULES: tuple[AuditRule, ...] = (
    AuditRule(
        rule_id="BOUNDARY-MODULE-001",
        category="boundary",
        severity="high",
        description="workflow.py and langgraph_workflow.py call active_reasoner.reason(reasoner_input); ReasonerInput does not carry credentials",
        check_function="check_workflow_reasoner_boundary",
    ),
    AuditRule(
        rule_id="BOUNDARY-MODULE-002",
        category="boundary",
        severity="high",
        description="LLMReasoner calls self.transport.complete(request); LLMTransportRequest does not carry credentials",
        check_function="check_reasoner_transport_boundary",
    ),
    AuditRule(
        rule_id="BOUNDARY-MODULE-003",
        category="boundary",
        severity="medium",
        description="OpenAICompatibleHTTPTransport.complete() returns LLMTransportResponse; adapt_openai_compatible_response() parses in independent module",
        check_function="check_transport_adapter_boundary",
    ),
    AuditRule(
        rule_id="BOUNDARY-MODULE-004",
        category="boundary",
        severity="high",
        description="ReasonerInput.candidate_values passed as immutable; runtime_validator.py validates suggested_value must belong to candidate set",
        check_function="check_candidate_reasoner_boundary",
    ),
    AuditRule(
        rule_id="BOUNDARY-MODULE-005",
        category="boundary",
        severity="high",
        description="runtime_validator.py independently validates Schema, references, rules, state, and summary; Workflow enters revision or manual intervention on failure",
        check_function="check_validator_workflow_boundary",
    ),
    AuditRule(
        rule_id="BOUNDARY-RESP-001",
        category="boundary",
        severity="high",
        description="ReasonerInput is immutable dataclass; Prompt template explicitly declares responsibilities that must not be modified",
        check_function="check_reasoner_immutability_resp",
    ),
    AuditRule(
        rule_id="BOUNDARY-RESP-002",
        category="boundary",
        severity="medium",
        description="AuditCollector record() only appends events; set_attempt_id() only updates collector context",
        check_function="check_audit_append_resp",
    ),
    AuditRule(
        rule_id="BOUNDARY-RESP-003",
        category="boundary",
        severity="high",
        description="require_config() throws RuleConfigError when path does not exist; no fallback provided",
        check_function="check_config_no_fallback",
    ),
    AuditRule(
        rule_id="BOUNDARY-RESP-004",
        category="boundary",
        severity="medium",
        description="evaluator.py reuses formal Workflow, Schema, and Runtime Validator",
        check_function="check_evaluator_reuse",
    ),
    AuditRule(
        rule_id="BOUNDARY-IFACE-001",
        category="boundary",
        severity="high",
        description="Reasoner Protocol defines def reason(self, reasoner_input: ReasonerInput) -> ReasonerResult",
        check_function="check_reasoner_protocol_signature",
    ),
    AuditRule(
        rule_id="BOUNDARY-IFACE-002",
        category="boundary",
        severity="high",
        description="LLMTransport Protocol defines def complete(self, request: LLMTransportRequest) -> LLMTransportResponse",
        check_function="check_transport_protocol_signature",
    ),
    AuditRule(
        rule_id="BOUNDARY-IFACE-003",
        category="boundary",
        severity="medium",
        description="schema_loader.py has independent validate_task_input, validate_agent_output, validate_failure_analysis, validate_manual_intervention_package, validate_audit_event",
        check_function="check_schema_validation_independence",
    ),
    AuditRule(
        rule_id="BOUNDARY-IFACE-004",
        category="boundary",
        severity="medium",
        description="langgraph_workflow.py route_after_evidence, route_after_validation, route_after_reasoner define explicit routing logic",
        check_function="check_langgraph_routing",
    ),
    AuditRule(
        rule_id="BOUNDARY-IFACE-005",
        category="boundary",
        severity="high",
        description="Runtime Validator validates suggested_value must belong to candidate_values; violation returns ERR_CANDIDATE_OUT_OF_RANGE",
        check_function="check_candidate_validation",
    ),
)

ALL_DEFAULT_RULES: tuple[AuditRule, ...] = DEFAULT_SECURITY_RULES + DEFAULT_COMPLIANCE_RULES + DEFAULT_BOUNDARY_RULES