# Generated by Django 5.2.16 on 2026-07-28 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=96, unique=True)),
                ("name", models.CharField(max_length=160)),
            ],
            options={
                "db_table": "sys_permission",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("code", models.CharField(max_length=96, unique=True)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roles",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "org_role",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_permissions",
                        to="permissions.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_permissions",
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "db_table": "org_role_permission",
            },
        ),
        migrations.CreateModel(
            name="TeamProfileAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "VIEW"),
                            (20, "OPERATE"),
                            (30, "APPROVE"),
                            (40, "EXECUTE"),
                            (50, "MANAGE"),
                        ]
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_access_grants",
                        to="stores.advertisingprofile",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile_access_grants",
                        to="tenants.team",
                    ),
                ),
            ],
            options={
                "db_table": "org_team_profile_access",
            },
        ),
        migrations.CreateModel(
            name="TeamStoreAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_access_grants",
                        to="stores.amazonstore",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="store_access_grants",
                        to="tenants.team",
                    ),
                ),
            ],
            options={
                "db_table": "org_team_store_access",
            },
        ),
        migrations.CreateModel(
            name="UserProfileAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "VIEW"),
                            (20, "OPERATE"),
                            (30, "APPROVE"),
                            (40, "EXECUTE"),
                            (50, "MANAGE"),
                        ]
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_access_grants",
                        to="stores.advertisingprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile_access_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "org_user_profile_access",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_roles",
                        to="tenants.tenantmembership",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_roles",
                        to="permissions.role",
                    ),
                ),
            ],
            options={
                "db_table": "org_user_role",
            },
        ),
        migrations.CreateModel(
            name="UserStoreAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_access_grants",
                        to="stores.amazonstore",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="store_access_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "org_user_store_access",
            },
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_system", True), ("tenant__isnull", True)),
                    models.Q(("is_system", False), ("tenant__isnull", False)),
                    _connector="OR",
                ),
                name="org_role_system_tenant_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="org_role_permission_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="teamprofileaccess",
            constraint=models.UniqueConstraint(
                fields=("team", "profile"), name="org_team_profile_access_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="teamstoreaccess",
            constraint=models.UniqueConstraint(
                fields=("team", "store"), name="org_team_store_access_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofileaccess",
            constraint=models.UniqueConstraint(
                fields=("user", "profile"), name="org_user_profile_access_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                fields=("membership", "role"), name="org_user_role_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="userstoreaccess",
            constraint=models.UniqueConstraint(
                fields=("user", "store"), name="org_user_store_access_uniq"
            ),
        ),
    ]
