# Generated by Django 5.2.16 on 2026-07-28 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("PARTIAL_SUCCEEDED", "Partial succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report_import_task",
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("PARTIAL_SUCCEEDED", "Partial succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("succeeded_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                ("normalized_rows_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch",
                        to="reports.importtask",
                    ),
                ),
            ],
            options={
                "db_table": "report_import_batch",
            },
        ),
        migrations.CreateModel(
            name="ReportUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("CAMPAIGN", "Campaign"),
                            ("TARGETING", "Targeting"),
                            ("SEARCH_TERM", "Search Term"),
                        ],
                        max_length=32,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=128)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("storage_path", models.CharField(max_length=500)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_duplicate", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stores.advertisingprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report_upload",
            },
        ),
        migrations.AddField(
            model_name="importtask",
            name="upload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="reports.reportupload",
            ),
        ),
        migrations.CreateModel(
            name="ImportRowError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("code", models.CharField(max_length=64)),
                ("field", models.CharField(blank=True, max_length=128)),
                ("message", models.CharField(max_length=500)),
                ("raw_excerpt", models.JSONField(default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="row_errors",
                        to="reports.importbatch",
                    ),
                ),
            ],
            options={
                "db_table": "report_import_row_error",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "row_number", "code", "field"),
                        name="report_row_error_uniq",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="reportupload",
            index=models.Index(
                fields=["profile", "report_type", "sha256"],
                name="report_upload_duplicate_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="importtask",
            index=models.Index(
                fields=["status", "created_at"], name="report_task_status_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="importtask",
            constraint=models.UniqueConstraint(
                fields=("upload", "idempotency_key"),
                name="report_task_upload_idempotency_uniq",
            ),
        ),
    ]
