# Generated by Django 5.2.16 on 2026-07-28 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("PARTIAL_SUCCEEDED", "Partially succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=32,
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=128)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("success_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=96)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_import_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reprocessed_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reprocess_attempts",
                        to="reports.importtask",
                    ),
                ),
            ],
            options={
                "db_table": "report_import_task",
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_version", models.CharField(max_length=32)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                (
                    "normalized_storage_key",
                    models.CharField(blank=True, max_length=500),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch",
                        to="reports.importtask",
                    ),
                ),
            ],
            options={
                "db_table": "report_import_batch",
            },
        ),
        migrations.CreateModel(
            name="ReportUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("CAMPAIGN", "Campaign"),
                            ("TARGETING", "Targeting"),
                            ("SEARCH_TERM", "Search term"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("FILE_UPLOAD", "File upload"),
                            ("THIRD_PARTY", "Third party"),
                            ("AMAZON_ADS_API", "Amazon Ads API"),
                        ],
                        default="FILE_UPLOAD",
                        max_length=32,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=128)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("storage_key", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="duplicates",
                        to="reports.reportupload",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_uploads",
                        to="stores.advertisingprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_uploads",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report_upload",
            },
        ),
        migrations.AddField(
            model_name="importtask",
            name="upload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_tasks",
                to="reports.reportupload",
            ),
        ),
        migrations.CreateModel(
            name="ImportRowError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("error_code", models.CharField(max_length=96)),
                ("message", models.CharField(max_length=1000)),
                ("field_name", models.CharField(blank=True, max_length=128)),
                ("rejected_value", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="row_errors",
                        to="reports.importtask",
                    ),
                ),
            ],
            options={
                "db_table": "report_import_row_error",
                "indexes": [
                    models.Index(
                        fields=["task", "row_number"],
                        name="report_row_error_task_row_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="reportupload",
            index=models.Index(
                fields=["tenant", "profile", "report_type", "-created_at"],
                name="report_up_scope_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportupload",
            index=models.Index(
                fields=["tenant", "sha256"], name="report_upload_tenant_hash_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importtask",
            index=models.Index(
                fields=["status", "created_at"], name="report_task_status_created_idx"
            ),
        ),
    ]
