# Generated by Django 5.2.16 on 2026-07-28 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [("advertising", "0001_initial"), ("advertising", "0002_initial")]

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_campaign_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("SPONSORED_PRODUCTS", "Sponsored Products"),
                            ("SPONSORED_BRANDS", "Sponsored Brands (reserved)"),
                            ("SPONSORED_DISPLAY", "Sponsored Display (reserved)"),
                        ],
                        default="SPONSORED_PRODUCTS",
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "daily_budget",
                    models.DecimalField(decimal_places=2, max_digits=14, null=True),
                ),
                ("currency", models.CharField(max_length=3)),
                ("source_batch_id", models.UUIDField(null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="stores.advertisingprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ads_campaign",
            },
        ),
        migrations.CreateModel(
            name="AdGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_ad_group_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_groups",
                        to="advertising.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "ads_ad_group",
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_keyword_id", models.CharField(max_length=128)),
                ("text", models.CharField(max_length=255)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("BROAD", "Broad"),
                            ("PHRASE", "Phrase"),
                            ("EXACT", "Exact"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="advertising.adgroup",
                    ),
                ),
            ],
            options={
                "db_table": "ads_keyword",
            },
        ),
        migrations.CreateModel(
            name="NegativeKeyword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("BROAD", "Broad"),
                            ("PHRASE", "Phrase"),
                            ("EXACT", "Exact"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "ad_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negative_keywords",
                        to="advertising.adgroup",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negative_keywords",
                        to="advertising.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "ads_negative_keyword",
            },
        ),
        migrations.CreateModel(
            name="ProductTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_target_id", models.CharField(max_length=128)),
                ("expression", models.CharField(max_length=500)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="advertising.adgroup",
                    ),
                ),
            ],
            options={
                "db_table": "ads_product_target",
            },
        ),
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_text", models.CharField(max_length=255)),
                ("targeting_text", models.CharField(blank=True, max_length=255)),
                ("source_batch_id", models.UUIDField(null=True)),
                (
                    "ad_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_terms",
                        to="advertising.adgroup",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_terms",
                        to="advertising.campaign",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_terms",
                        to="stores.advertisingprofile",
                    ),
                ),
            ],
            options={
                "db_table": "ads_search_term",
            },
        ),
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_ad_id", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ads",
                        to="products.productlisting",
                    ),
                ),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to="advertising.adgroup",
                    ),
                ),
            ],
            options={
                "db_table": "ads_ad",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ad_group", "external_ad_id"),
                        name="ads_ad_group_external_uniq",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["profile", "state"], name="ads_campaign_profile_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.UniqueConstraint(
                fields=("profile", "external_campaign_id"),
                name="ads_campaign_profile_external_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="adgroup",
            constraint=models.UniqueConstraint(
                fields=("campaign", "external_ad_group_id"),
                name="ads_adgroup_campaign_external_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="keyword",
            constraint=models.UniqueConstraint(
                fields=("ad_group", "external_keyword_id"),
                name="ads_keyword_group_external_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="producttarget",
            constraint=models.UniqueConstraint(
                fields=("ad_group", "external_target_id"),
                name="ads_target_group_external_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchterm",
            constraint=models.UniqueConstraint(
                fields=("profile", "query_text", "targeting_text"),
                name="ads_search_term_profile_query_target_uniq",
            ),
        ),
    ]
