# Generated by Django 5.2.16 on 2026-07-28 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_ad_id", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "ads_ad",
            },
        ),
        migrations.CreateModel(
            name="AdGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_ad_group_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "ads_ad_group",
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_campaign_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("SPONSORED_PRODUCTS", "Sponsored Products"),
                            ("SPONSORED_BRANDS", "Sponsored Brands (reserved)"),
                            ("SPONSORED_DISPLAY", "Sponsored Display (reserved)"),
                        ],
                        default="SPONSORED_PRODUCTS",
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "daily_budget",
                    models.DecimalField(decimal_places=2, max_digits=14, null=True),
                ),
                ("currency", models.CharField(max_length=3)),
                ("source_batch_id", models.UUIDField(null=True)),
            ],
            options={
                "db_table": "ads_campaign",
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_keyword_id", models.CharField(max_length=128)),
                ("text", models.CharField(max_length=255)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("BROAD", "Broad"),
                            ("PHRASE", "Phrase"),
                            ("EXACT", "Exact"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(decimal_places=2, max_digits=14, null=True),
                ),
            ],
            options={
                "db_table": "ads_keyword",
            },
        ),
        migrations.CreateModel(
            name="NegativeKeyword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("BROAD", "Broad"),
                            ("PHRASE", "Phrase"),
                            ("EXACT", "Exact"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "ads_negative_keyword",
            },
        ),
        migrations.CreateModel(
            name="ProductTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_target_id", models.CharField(max_length=128)),
                ("expression", models.CharField(max_length=500)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(decimal_places=2, max_digits=14, null=True),
                ),
            ],
            options={
                "db_table": "ads_product_target",
            },
        ),
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query_text", models.CharField(max_length=500)),
                ("targeting_text", models.CharField(blank=True, max_length=500)),
                ("source_batch_id", models.UUIDField(null=True)),
            ],
            options={
                "db_table": "ads_search_term",
            },
        ),
    ]
