# Generated by Django 5.2.16 on 2026-07-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_ad_id", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "ads_ad",
            },
        ),
        migrations.CreateModel(
            name="AdGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_ad_group_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                (
                    "default_bid",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ads_ad_group",
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_campaign_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                (
                    "ad_product_type",
                    models.CharField(
                        choices=[
                            ("SP", "Sponsored Products"),
                            ("SB", "Sponsored Brands"),
                            ("SD", "Sponsored Display"),
                        ],
                        default="SP",
                        max_length=8,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                (
                    "daily_budget",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("currency_code", models.CharField(max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ads_campaign",
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_keyword_id", models.CharField(max_length=128)),
                ("keyword_text", models.CharField(max_length=500)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("BROAD", "Broad"),
                            ("PHRASE", "Phrase"),
                            ("EXACT", "Exact"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_negative", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
            ],
            options={
                "db_table": "ads_keyword",
            },
        ),
        migrations.CreateModel(
            name="ProductTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_target_id", models.CharField(max_length=128)),
                ("expression", models.CharField(max_length=1000)),
                ("is_negative", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ENABLED", "Enabled"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=16,
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
            ],
            options={
                "db_table": "ads_product_target",
            },
        ),
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("normalized_text", models.CharField(max_length=1000)),
                ("text_hash", models.CharField(max_length=64)),
                ("display_text", models.CharField(max_length=1000)),
            ],
            options={
                "db_table": "ads_search_term",
            },
        ),
    ]
