# Generated by Django 5.2.16 on 2026-07-28 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advertising", "0001_initial"),
        ("products", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ads",
                to="products.productlisting",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="ad_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                to="advertising.adgroup",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="stores.advertisingprofile",
            ),
        ),
        migrations.AddField(
            model_name="adgroup",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ad_groups",
                to="advertising.campaign",
            ),
        ),
        migrations.AddField(
            model_name="keyword",
            name="ad_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keywords",
                to="advertising.adgroup",
            ),
        ),
        migrations.AddField(
            model_name="negativekeyword",
            name="ad_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negative_keywords",
                to="advertising.adgroup",
            ),
        ),
        migrations.AddField(
            model_name="negativekeyword",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negative_keywords",
                to="advertising.campaign",
            ),
        ),
        migrations.AddField(
            model_name="producttarget",
            name="ad_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="advertising.adgroup",
            ),
        ),
        migrations.AddField(
            model_name="searchterm",
            name="ad_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_terms",
                to="advertising.adgroup",
            ),
        ),
        migrations.AddField(
            model_name="searchterm",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_terms",
                to="advertising.campaign",
            ),
        ),
        migrations.AddField(
            model_name="searchterm",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_terms",
                to="stores.advertisingprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="ad",
            constraint=models.UniqueConstraint(
                fields=("ad_group", "external_ad_id"), name="ads_ad_group_external_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["profile", "state"], name="ads_campaign_profile_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.UniqueConstraint(
                fields=("profile", "external_campaign_id"),
                name="ads_campaign_profile_external_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="adgroup",
            constraint=models.UniqueConstraint(
                fields=("campaign", "external_ad_group_id"),
                name="ads_adgroup_campaign_external_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="keyword",
            constraint=models.UniqueConstraint(
                fields=("ad_group", "external_keyword_id"),
                name="ads_keyword_group_external_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="producttarget",
            constraint=models.UniqueConstraint(
                fields=("ad_group", "external_target_id"),
                name="ads_target_group_external_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchterm",
            constraint=models.UniqueConstraint(
                fields=("profile", "query_text", "targeting_text"),
                name="ads_search_term_profile_query_target_uniq",
            ),
        ),
    ]
