# Generated by Django 5.2.16 on 2026-07-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='target_acos',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
    ]
