# Generated by Django 5.2.16 on 2026-07-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising", "0003_campaign_target_acos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchterm",
            name="query_text",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="searchterm",
            name="targeting_text",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
