# Generated by Django 5.2.16 on 2026-07-28 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("item_index", models.PositiveIntegerField()),
                ("action", models.JSONField()),
                ("status", models.CharField(default="PENDING", max_length=16)),
            ],
            options={
                "db_table": "action_execution_item",
            },
        ),
        migrations.CreateModel(
            name="ActionPreview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("RETURNED", "Returned"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("current_version", models.PositiveIntegerField(default=1)),
                ("version_lock", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stores.advertisingprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenants.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "action_preview",
            },
        ),
        migrations.CreateModel(
            name="ActionPreviewVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("items", models.JSONField()),
                ("content_hash", models.CharField(max_length=64)),
                ("frozen_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "preview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="actions.actionpreview",
                    ),
                ),
            ],
            options={
                "db_table": "action_preview_version",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("decision", models.CharField(max_length=32)),
                ("comment", models.CharField(blank=True, max_length=500)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to="actions.actionpreview",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="actions.actionpreviewversion",
                    ),
                ),
            ],
            options={
                "db_table": "action_approval_record",
            },
        ),
        migrations.CreateModel(
            name="ExecutionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("result", models.CharField(max_length=16)),
                ("actual_value", models.JSONField(default=dict)),
                ("executed_at", models.DateTimeField()),
                ("note", models.CharField(blank=True, max_length=500)),
                ("evidence_path", models.CharField(blank=True, max_length=500)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="actions.executionitem",
                    ),
                ),
            ],
            options={
                "db_table": "action_execution_record",
            },
        ),
        migrations.CreateModel(
            name="ExecutionTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(default="WAITING_CONFIRMATION", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "preview",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_task",
                        to="actions.actionpreview",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="actions.actionpreviewversion",
                    ),
                ),
            ],
            options={
                "db_table": "action_execution_task",
            },
        ),
        migrations.AddField(
            model_name="executionitem",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="actions.executiontask",
            ),
        ),
        migrations.CreateModel(
            name="EffectEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(max_length=16)),
                ("baseline", models.JSONField(default=dict)),
                ("observed", models.JSONField(default=dict)),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluations",
                        to="actions.executiontask",
                    ),
                ),
            ],
            options={
                "db_table": "action_effect_evaluation",
            },
        ),
        migrations.AddConstraint(
            model_name="actionpreviewversion",
            constraint=models.UniqueConstraint(
                fields=("preview", "version"), name="action_preview_version_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="approvalrecord",
            constraint=models.UniqueConstraint(
                fields=("preview", "idempotency_key"), name="action_approval_idem_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="executionrecord",
            constraint=models.UniqueConstraint(
                fields=("item", "idempotency_key"),
                name="action_execution_record_idem_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionitem",
            constraint=models.UniqueConstraint(
                fields=("task", "item_index"), name="action_execution_item_uniq"
            ),
        ),
    ]
