# Generated by Django 5.2.16 on 2026-07-28 12:42

import uuid
from django.conf import settings
from django.db import migrations, models


def populate_preview_idempotency_keys(apps, schema_editor):
    action_preview = apps.get_model("actions", "ActionPreview")
    for preview in action_preview.objects.filter(idempotency_key__isnull=True).iterator(
        chunk_size=500
    ):
        preview.idempotency_key = uuid.uuid4().hex
        preview.save(update_fields=["idempotency_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0001_initial"),
        ("stores", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="actionpreview",
            name="idempotency_key",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.RunPython(
            populate_preview_idempotency_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="actionpreview",
            name="idempotency_key",
            field=models.CharField(default=uuid.uuid4, max_length=128),
        ),
        migrations.AddIndex(
            model_name="actionpreview",
            index=models.Index(
                fields=["tenant", "profile", "status", "created_at"],
                name="action_preview_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="actionpreview",
            constraint=models.UniqueConstraint(
                fields=("tenant", "idempotency_key"),
                name="action_preview_tenant_idem_uniq",
            ),
        ),
    ]
