# Generated by Django 5.2.16 on 2026-07-28 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actions", "0001_initial"),
        ("recommendations", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="actionpreview",
            name="recommendation_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="action_previews",
                to="recommendations.recommendationrevision",
            ),
        ),
        migrations.AddField(
            model_name="actionpreview",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_action_previews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="actionpreview",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="action_previews",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="actionpreviewversion",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="action_preview_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="actionpreviewversion",
            name="preview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="actions.actionpreview",
            ),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="decided_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="preview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_records",
                to="actions.actionpreview",
            ),
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="preview_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_records",
                to="actions.actionpreviewversion",
            ),
        ),
        migrations.AddField(
            model_name="executionrecord",
            name="preview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="execution_records",
                to="actions.actionpreview",
            ),
        ),
        migrations.AddField(
            model_name="executionrecord",
            name="preview_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="execution_records",
                to="actions.actionpreviewversion",
            ),
        ),
        migrations.AddField(
            model_name="executionrecord",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="execution_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="actionpreview",
            index=models.Index(
                fields=["tenant", "profile", "status", "-created_at"],
                name="action_prev_scope_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="actionpreview",
            constraint=models.UniqueConstraint(
                fields=("recommendation_revision", "created_by"),
                name="action_preview_revision_creator_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="actionpreviewversion",
            constraint=models.UniqueConstraint(
                fields=("preview", "version_number"), name="action_preview_version_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="executionrecord",
            constraint=models.UniqueConstraint(
                fields=("preview", "preview_version"),
                name="action_execution_preview_version_uniq",
            ),
        ),
    ]
