from collections.abc import Iterable
from typing import BinaryIO, Protocol


class FileStorage(Protocol):
    def save(self, *, key: str, chunks: Iterable[bytes]) -> int: ...

    def open(self, *, key: str) -> BinaryIO: ...

    def exists(self, *, key: str) -> bool: ...

    def delete(self, *, key: str) -> None: ...
