# Generated by Django 5.2.16 on 2026-07-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marketplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("currency_code", models.CharField(max_length=3)),
                ("timezone", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ads_marketplace",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AmazonStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("external_store_id", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stores",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ads_store",
            },
        ),
        migrations.CreateModel(
            name="StoreMarketplace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="store_marketplaces",
                        to="stores.marketplace",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="store_marketplaces",
                        to="stores.amazonstore",
                    ),
                ),
            ],
            options={
                "db_table": "ads_store_marketplace",
            },
        ),
        migrations.CreateModel(
            name="AdvertisingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_profile_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=160)),
                ("currency_code", models.CharField(max_length=3)),
                ("timezone", models.CharField(max_length=64)),
                (
                    "target_acos",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store_marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advertising_profiles",
                        to="stores.storemarketplace",
                    ),
                ),
            ],
            options={
                "db_table": "ads_advertising_profile",
            },
        ),
        migrations.AddIndex(
            model_name="amazonstore",
            index=models.Index(
                fields=["tenant", "is_active"], name="ads_store_tenant_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="amazonstore",
            constraint=models.UniqueConstraint(
                fields=("tenant", "external_store_id"),
                name="ads_store_tenant_external_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="storemarketplace",
            index=models.Index(
                fields=["store", "is_active"], name="ads_store_market_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="storemarketplace",
            constraint=models.UniqueConstraint(
                fields=("store", "marketplace"), name="ads_store_marketplace_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="advertisingprofile",
            index=models.Index(
                fields=["store_marketplace", "is_active"],
                name="ads_profile_store_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="advertisingprofile",
            constraint=models.UniqueConstraint(
                fields=("store_marketplace", "external_profile_id"),
                name="ads_profile_store_market_ext_uniq",
            ),
        ),
    ]
