# Generated by Django 5.2.16 on 2026-07-28 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marketplace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("country_code", models.CharField(max_length=2)),
                ("currency", models.CharField(max_length=3)),
                ("timezone", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ads_marketplace",
            },
        ),
        migrations.CreateModel(
            name="AmazonStore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("external_store_id", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ads_store",
            },
        ),
        migrations.CreateModel(
            name="StoreMarketplace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seller_id", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="store_marketplaces",
                        to="stores.marketplace",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_marketplaces",
                        to="stores.amazonstore",
                    ),
                ),
            ],
            options={
                "db_table": "ads_store_marketplace",
            },
        ),
        migrations.CreateModel(
            name="AdvertisingProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("external_profile_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("account_type", models.CharField(default="SELLER", max_length=32)),
                ("currency", models.CharField(max_length=3)),
                ("timezone", models.CharField(max_length=64)),
                (
                    "target_acos",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store_marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="stores.storemarketplace",
                    ),
                ),
            ],
            options={
                "db_table": "ads_advertising_profile",
            },
        ),
        migrations.AddIndex(
            model_name="amazonstore",
            index=models.Index(
                fields=["tenant", "is_active"], name="ads_store_tenant_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="amazonstore",
            constraint=models.UniqueConstraint(
                fields=("tenant", "external_store_id"),
                name="ads_store_tenant_external_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="storemarketplace",
            constraint=models.UniqueConstraint(
                fields=("store", "marketplace"), name="ads_store_marketplace_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="advertisingprofile",
            index=models.Index(
                fields=["store_marketplace", "is_active"],
                name="ads_profile_scope_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="advertisingprofile",
            constraint=models.UniqueConstraint(
                fields=("store_marketplace", "external_profile_id"),
                name="ads_profile_scope_external_uniq",
            ),
        ),
    ]
