# Generated by Django 5.2.16 on 2026-07-28 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceCatalogItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asin", models.CharField(max_length=32)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_items",
                        to="stores.marketplace",
                    ),
                ),
            ],
            options={
                "db_table": "ads_marketplace_catalog_item",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("internal_code", models.CharField(max_length=128)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ads_product",
            },
        ),
        migrations.CreateModel(
            name="ProductListing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("seller_sku", models.CharField(max_length=128)),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings",
                        to="products.marketplacecatalogitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="products.product",
                    ),
                ),
                (
                    "store_marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="stores.storemarketplace",
                    ),
                ),
            ],
            options={
                "db_table": "ads_product_listing",
            },
        ),
        migrations.AddConstraint(
            model_name="marketplacecatalogitem",
            constraint=models.UniqueConstraint(
                fields=("marketplace", "asin"), name="ads_catalog_market_asin_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("tenant", "internal_code"), name="ads_product_tenant_code_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="productlisting",
            constraint=models.UniqueConstraint(
                fields=("store_marketplace", "seller_sku"),
                name="ads_listing_scope_sku_uniq",
            ),
        ),
    ]
