# Generated by Django 5.2.16 on 2026-07-28 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceCatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asin", models.CharField(max_length=32)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalog_items",
                        to="stores.marketplace",
                    ),
                ),
            ],
            options={
                "db_table": "ads_marketplace_catalog_item",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ads_product",
            },
        ),
        migrations.CreateModel(
            name="ProductListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seller_sku", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "catalog_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="products.marketplacecatalogitem",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="products.product",
                    ),
                ),
                (
                    "store_marketplace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_listings",
                        to="stores.storemarketplace",
                    ),
                ),
            ],
            options={
                "db_table": "ads_product_listing",
            },
        ),
        migrations.AddConstraint(
            model_name="marketplacecatalogitem",
            constraint=models.UniqueConstraint(
                fields=("marketplace", "asin"), name="ads_catalog_market_asin_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["tenant", "is_active"], name="ads_product_tenant_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productlisting",
            index=models.Index(
                fields=["product", "is_active"], name="ads_listing_product_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productlisting",
            constraint=models.UniqueConstraint(
                fields=("store_marketplace", "seller_sku"),
                name="ads_listing_store_market_sku_uniq",
            ),
        ),
    ]
